// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WearMatcher.Data;

namespace WearMatcher.Migrations
{
    [DbContext(typeof(WearMatcherContext))]
    partial class WearMatcherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClothingItemTag", b =>
                {
                    b.Property<int>("ClothingItemsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ClothingItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ClothingItemTag");
                });

            modelBuilder.Entity("WearMatcher.Models.ClothingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ImgPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClothingItem");
                });

            modelBuilder.Entity("WearMatcher.Models.MatchingItemsPair", b =>
                {
                    b.Property<int>("FirstItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondItemId")
                        .HasColumnType("integer");

                    b.HasKey("FirstItemId", "SecondItemId");

                    b.HasIndex("SecondItemId");

                    b.ToTable("MatchingItemsPair");
                });

            modelBuilder.Entity("WearMatcher.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ClothingItemTag", b =>
                {
                    b.HasOne("WearMatcher.Models.ClothingItem", null)
                        .WithMany()
                        .HasForeignKey("ClothingItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WearMatcher.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WearMatcher.Models.MatchingItemsPair", b =>
                {
                    b.HasOne("WearMatcher.Models.ClothingItem", "FirstItem")
                        .WithMany("ItemItem")
                        .HasForeignKey("FirstItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WearMatcher.Models.ClothingItem", "SecondItem")
                        .WithMany()
                        .HasForeignKey("SecondItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstItem");

                    b.Navigation("SecondItem");
                });

            modelBuilder.Entity("WearMatcher.Models.ClothingItem", b =>
                {
                    b.Navigation("ItemItem");
                });
#pragma warning restore 612, 618
        }
    }
}
